[data]
data_path          = "/proj/berzelius-2025-380/storage/hest1k/kidney/"
processed_subdir   = "processed_data"
st_subdir          = "st"
slide_out          = "NCBI694"
gene_list_filename = "selected_gene_list_200_hmhvg.txt"

[baseline]
save_dir = "/proj/berzelius-2025-380/storage/felipe/workspace/Stem_stomics/results/spot_mean_oracle/kidney_hmhvg/"
num_rep  = 1
